---
# tasks file for install_pool

- name: set fact according to actual pool config
  ansible.builtin.set_fact:
    _pool_is_configured: 'true'
  run_once: true

- name: check for actual pool config
  ansible.builtin.shell:
    cmd: "om pool ls | grep -w {{ osvc_pool_name }}"
  failed_when: false
  changed_when: false
  register: _osvc_pool_list
  run_once: true

- name: set fact according to actual pool existence
  ansible.builtin.set_fact:
    _pool_is_configured: 'false'
  run_once: true
  when:
    - osvc_pool_name not in _osvc_pool_list.stdout

- name: display pool existence flag
  ansible.builtin.debug:
    var: _pool_is_configured
    verbosity: 2

- name: configure directory pool
  include_tasks: "directory.yml"
  when:
    - not _pool_is_configured 
    - osvc_pool_type == "directory"

- name: configure drbd pool
  include_tasks: "drbd.yml"
  when:
    - not _pool_is_configured 
    - osvc_pool_type == "drbd"
