---
# defaults file for install_cni

install_cni_plugins_dir: "/usr/libexec/cni/bin"

install_cni_config_dir: "/var/lib/opensvc/cni/net.d"

install_cni_plugin_binaries: ['macvlan', 'ipvlan', 'vlan', 'flannel', 'bridge']

install_cni_download_url_version:
  v0.8.5:
    url: "https://github.com/containernetworking/plugins/releases/download/v0.8.5/cni-plugins-linux-amd64-v0.8.5.tgz"
    dest: "/tmp/cni-plugins-amd64-v0.8.5.tgz"
    checksum: "sha1:677d218b62c0ef941c1d0b606d6570faa5277ffd"
  v0.9.1:
    url: "https://github.com/containernetworking/plugins/releases/download/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz"
    dest: "/tmp/cni-plugins-amd64-v0.9.1.tgz"
    checksum: "sha1:4a47eea0a27d1b07c90d5d11080d55e13ba76608"
  v1.6.2:
    url: "https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-amd64-v1.6.2.tgz"
    dest: "/tmp/cni-plugins-amd64-v1.6.2.tgz"
    checksum: "sha1:501d208a15566ce0f6baeb62cb8f53deb3f036e3"

install_cni_version: "v1.6.2"

install_cni_download_url: "{{ install_cni_download_url_version[install_cni_version] }}"
