---
# tasks file for unprovision_services

- name: Freeze cluster
  ansible.builtin.command: "om cluster freeze"
  register: output
  changed_when: output.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Check cluster vip current config
  ansible.builtin.command: "om cluster get --kw cluster.vip --eval"
  register: osvc_cluster_vip
  changed_when: false
  failed_when: false

- name: Consider that vip is not configured
  ansible.builtin.set_fact:
    osvc_cluster_vip_is_configured: false

- name: Check if vip is actually configured
  ansible.builtin.set_fact:
    osvc_cluster_vip_is_configured: true
  when:
    - osvc_cluster_vip.stdout.find('None') == -1

- name: Display osvc_cluster_vip_is_configured variable content
  ansible.builtin.debug:
    var: osvc_cluster_vip_is_configured
    verbosity: 2

- name: Unconfigure cluster vip
  ansible.builtin.command: om cluster unset --kw cluster.vip
  register: output
  changed_when: output.rc == 0
  when:
    - osvc_cluster_vip_is_configured | bool
    - inventory_hostname == ansible_play_hosts[0]

- name: Unconfigure cluster vip (scoped entries)
  ansible.builtin.command: "om cluster unset --kw cluster.vip@{{ ansible_hostname }}"
  register: output
  changed_when: output.rc == 0
  when:
    - osvc_cluster_vip_is_configured|bool

- name: Consider that we do not need to purge anything
  ansible.builtin.set_fact:
    osvc_cluster_need_svc_purge: false
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Check if we actually need to purge something
  ansible.builtin.shell: |
    set -o pipefail && om '*/*/*+!*/*/cluster+!system/sec/cert+!system/sec/ca' ls | grep -v ^OBJECT | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: osvc_cluster_svc_count
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Update fact
  ansible.builtin.set_fact:
    osvc_cluster_need_svc_purge: true
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_svc_count.rc == 0 and osvc_cluster_svc_count.stdout|int > 0

- name: Purge all OpenSVC services
  ansible.builtin.shell: |
    set -o pipefail && om '*/*/*+!*/*/cluster+!system/sec/cert+!system/sec/ca' purge --wait --time {{ unprovision_services_purge_wait_time }}
  args:
    executable: /bin/bash
  register: output
  changed_when: output.rc == 0
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_need_svc_purge|bool

- name: Check for actual service unprov
  ansible.builtin.shell: |
    set -o pipefail && om '*/*/*+!*/*/cluster+!system/sec/cert+!system/sec/ca' ls | grep -v ^OBJECT | wc -l
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: false
  register: osvc_cluster_svc_unprov_cmdres
  retries: "{{ unprovision_services_purge_retries }}"
  delay: "{{ unprovision_services_purge_delay }}"
  until: osvc_cluster_svc_unprov_cmdres.stdout == '0'
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_need_svc_purge | bool
