---
# tasks file for install_dns

- name: set fact on dns cfgmap creation
  ansible.builtin.set_fact:
    dns_cfg_created: 'true'
  run_once: true

- name: check for dns cfgmap existence
  command: om system/cfg/dns ls
  changed_when: false
  register: osvc_dns_cfgmap_query
  run_once: true

- name: set fact according to actual dns cfgmap existence
  ansible.builtin.set_fact:
    dns_cfg_created: 'false'
  run_once: true
  when:
    - osvc_dns_cfgmap_name not in osvc_dns_cfgmap_query.stdout

- name: create dns cfgmap
  command: om {{ osvc_dns_cfgmap_name }} create
  run_once: true
  when:
    - not dns_cfg_created

- name: set dns cfgmap server key content
  command: om {{ osvc_dns_cfgmap_name }} add --key server --from {{ osvc_dns_cfg_server_template }}
  run_once: true
  when:
    - not dns_cfg_created

- name: set dns cfgmap recursor key content
  command: om {{ osvc_dns_cfgmap_name }} add --key recursor --from {{ osvc_dns_cfg_recursor_template }}
  run_once: true
  when:
    - not dns_cfg_created

- name: set dns cfgmap configure key content
  command: om {{ osvc_dns_cfgmap_name }} add --key configure --from {{ osvc_dns_cfg_configure_template }}
  run_once: true
  when:
    - not dns_cfg_created

- name: set fact on dns service creation
  ansible.builtin.set_fact:
    dns_svc_created: 'true'
  run_once: true

- name: check for dns svc existence
  command: om {{ osvc_dns_service_name }} ls
  changed_when: false
  register: osvc_dns_svc_query
  run_once: true

- name: set fact according to actual dns svc existence
  ansible.builtin.set_fact:
    dns_svc_created: 'false'
  run_once: true
  when:
    - osvc_dns_service_name not in osvc_dns_svc_query.stdout

- name: define osvc_dns1_ip_addr variable
  ansible.builtin.set_fact:
    osvc_dns1_ip_addr: "{{ hostvars[ansible_play_hosts[0]].ansible_default_ipv4.address }}"
  run_once: true
  when:
    - not dns_svc_created

- name: define osvc_dns2_ip_addr variable
  ansible.builtin.set_fact:
    osvc_dns2_ip_addr: "{{ hostvars[ansible_play_hosts[1]].ansible_default_ipv4.address }}"
  run_once: true
  when:
    - nodecount|int > 1
    - not dns_svc_created

- name: configure cluster dns thread when node count greater than 1
  command: om cluster set --kw 'cluster.dns={{ osvc_dns1_ip_addr }} {{ osvc_dns2_ip_addr }}'
  run_once: true
  when:
    - nodecount|int > 1
    - not dns_svc_created

- name: configure cluster dns thread when node count is 1
  command: om cluster set --kw 'cluster.dns={{ osvc_dns1_ip_addr }}'
  run_once: true
  when:
    - nodecount|int == 1
    - not dns_svc_created

- name: Check for dns.cluster propagation before provisioning service
  command: om cluster get --kw cluster.dns
  changed_when: false
  register: cmd_res
  retries: 20
  delay: 2
  until: cmd_res.stdout.find(osvc_dns2_ip_addr)
  when:
    - nodecount|int > 1
    - not dns_svc_created
    - inventory_hostname != ansible_play_hosts[0]

- name: deploy dns service
  command: om {{ osvc_dns_service_name }} deploy --config {{ osvc_dns_svc_template }}
  run_once: true
  when:
    - not dns_svc_created
