---
# vars file for install_collector

# target opensvc namespace to host the collector objects
install_collector_namespace: "prod"

install_collector_nginx_conf_file: "https://raw.githubusercontent.com/opensvc/opensvc_templates/main/collector/nginx.conf"
install_collector_dbdump_script: "https://raw.githubusercontent.com/opensvc/opensvc_templates/main/collector/scripts/dbdump.sh"
install_collector_dbrestore_script: "https://raw.githubusercontent.com/opensvc/opensvc_templates/main/collector/scripts/dbrestore.sh"
install_collector_dbtables_list: "https://raw.githubusercontent.com/opensvc/opensvc_templates/main/collector/scripts/dbdump.tables"

install_collector_db_password: "opensvc"
install_collector_web2py_admin_console_password: "opensvc"
install_collector_repo: "https://github.com/opensvc/collector"

install_collector_service_config: "https://raw.githubusercontent.com/opensvc/opensvc_templates/main/collector/collector.conf"

install_collector_network_host: false
