---

- name: Set facts on collector service creation
  ansible.builtin.set_fact:
    osvc_collector_svc_created: 'true'
  run_once: true

- name: Check for collector svc existence
  ansible.builtin.command: om {{ install_collector_environ_svcname }} ls
  changed_when: false
  register: osvc_collector_svcname_query
  run_once: true

- name: Set fact according to actual collector svc existence
  ansible.builtin.set_fact:
    osvc_collector_svc_created: 'false'
  run_once: true
  when:
    - install_collector_environ_svcname not in osvc_collector_svcname_query.stdout

- name: Create collector service
  ansible.builtin.command: >
           om {{ install_collector_environ_svcname }} create
           --config {{ install_collector_service_config }}
  run_once: true
  register: output
  changed_when: output.rc == 0
  when:
    - not osvc_collector_svc_created

- name: Configure network to share host netns
  ansible.builtin.include_tasks: "net.host.yml"
  run_once: true
  when:
    - install_collector_network_host
    - not osvc_collector_svc_created

- name: Provision collector service
  ansible.builtin.command: "om {{ install_collector_environ_svcname }} provision --wait"
  run_once: true
  register: output
  changed_when: output.rc == 0
  when:
    - not osvc_collector_svc_created
