---
# tasks file for install_collector
#

- name: Install environment secrets
  ansible.builtin.include_tasks: "secrets.yml"

- name: Install environment configmaps
  ansible.builtin.include_tasks: "configmaps.yml"

- name: Deploy collector service
  ansible.builtin.include_tasks: "collector.yml"
