---

- name: set facts on environment secrets creation
  ansible.builtin.set_fact:
    osvc_collector_environ_sec_created: 'true'
  run_once: true

- name: check for environment secrets existence
  command: om {{ osvc_collector_environ_secname }} ls
  changed_when: false
  register: osvc_collector_environ_secname_query
  run_once: true

- name: set fact according to actual environment secrets existence
  ansible.builtin.set_fact:
    osvc_collector_environ_sec_created: 'false'
  run_once: true
  when:
    - >
      osvc_collector_environ_secname
      not in
      osvc_collector_environ_secname_query.stdout

- name: create environment secrets
  command: om {{ osvc_collector_environ_secname }} create
  run_once: true
  when:
    - not osvc_collector_environ_sec_created

- name: generate ssl certificates
  command: om {{ osvc_collector_environ_secname }} gen cert
  run_once: true
  when:
    - not osvc_collector_environ_sec_created

- name: load environment secrets variable
  command: >
           om {{ osvc_collector_environ_secname }}
           add --key {{ item.key }} --value {{ item.value }}
  run_once: true
  when:
    - not osvc_collector_environ_sec_created
  with_items:
    - {key: "db_password", value: "{{ osvc_collector_db_password }}"}
    - >
      {
       key: "CUSTO_WEB2PY_ADMIN_CONSOLE_PWD",
       value: "{{ osvc_collector_web2py_admin_console_password }}"
      }
    - {key: "repo", value: "{{ osvc_collector_repo }}"}
