---

- name: Set facts on environment secrets creation
  ansible.builtin.set_fact:
    osvc_collector_environ_sec_created: 'true'
  run_once: true

- name: Check for environment secrets existence
  ansible.builtin.command: om {{ install_collector_environ_secname }} ls
  changed_when: false
  register: install_collector_environ_secname_query
  run_once: true

- name: Set fact according to actual environment secrets existence
  ansible.builtin.set_fact:
    osvc_collector_environ_sec_created: 'false'
  run_once: true
  when:
    - >
      install_collector_environ_secname
      not in
      install_collector_environ_secname_query.stdout

- name: Create environment secrets
  ansible.builtin.command: om {{ install_collector_environ_secname }} create
  run_once: true
  register: output
  changed_when: output.rc == 0
  when:
    - not osvc_collector_environ_sec_created

- name: Generate ssl certificates
  ansible.builtin.command: om {{ install_collector_environ_secname }} gen cert
  run_once: true
  register: output
  changed_when: output.rc == 0
  when:
    - not osvc_collector_environ_sec_created

- name: Load environment secrets variable
  ansible.builtin.command: >
           om {{ install_collector_environ_secname }}
           add --key {{ item.key }} --value {{ item.value }}
  run_once: true
  register: output
  changed_when: output.rc == 0
  when:
    - not osvc_collector_environ_sec_created
  with_items:
    - {key: "db_password", value: "{{ install_collector_db_password }}"}
    - {key: "CUSTO_WEB2PY_ADMIN_CONSOLE_PWD",
       value: "{{ install_collector_web2py_admin_console_password }}"}
    - {key: "repo", value: "{{ install_collector_repo }}"}
