---
# defaults file for provision_cluster

# set to something unique
provision_cluster_osvc_clustername: demo

# time waited before considering hb as down
provision_cluster_osvc_hb_timeout: 20s

# update /etc/hosts to add each cluster node ip
# false: you deal with this setup by yourself
# true: you expect the playbook to do the config
provision_cluster_osvc_update_etc_hosts: false

# depending on your cluster setup, you may need to disable default docker behavior with iptables
# if false, do not change /etc/docker/daemon.json config file
# if true, override /etc/docker/daemon.json content with iptables=false
provision_cluster_osvc_deploy_docker_daemon_json: false

# when docker daemon config deployment is enabled, we need to restart the docker service
provision_cluster_systemd_docker_unit: 'docker.service'

# configure the cluster virtual ip
# recommended for streched vlans setup
# clients can connect to webapp/api using this floating ip
provision_cluster_osvc_configure_vip: false
provision_cluster_osvc_cluster_vip_addr: '1.2.3.4'
provision_cluster_osvc_cluster_vip_cidr_subnet: '24'
# vip ip addr will be configured on link vipnic@br-prd (displayed with "ip link list")
provision_cluster_osvc_cluster_vip_nic_name: 'vipnic'
provision_cluster_osvc_node_prd_nic: 'br0'
# public fqdn https://vip.domain.com:1215
provision_cluster_osvc_vip_external_fqdn: 'vip.domain.com'

# configure the 1215/tcp port for webapp and api usage
provision_cluster_osvc_configure_webapp: false
# cluster admin credentials (webapp/api)
provision_cluster_osvc_webapp_user: 'admin'
provision_cluster_osvc_webapp_password: 's3cr3t'

# webapp/api are served through tls / http/2
# we have to autoconfigue ssl certs
# by default 'self' mode create a per-cluster CA and self-signed certs for 1215/tcp listener
# other modes can be configured, please contact support@opensvc.com
provision_cluster_osvc_ca_cert_mode: 'self'
provision_cluster_osvc_ca_cert_name: 'TEST CLUSTER'
provision_cluster_osvc_ca_cert_country: 'US'
provision_cluster_osvc_ca_cert_org: 'ACME Company'

# opensvc repository
provision_cluster_osvc_repo_url: "https://repo.opensvc.com/{{ 'deb' if ansible_os_family == 'Debian' else 'rpms' }}/current"
provision_cluster_osvc_pkg_dl_path: "/tmp/opensvc.latest.{{ 'deb' if ansible_os_family == 'Debian' else 'rpm' }}"
