FROM python:3.9.17-alpine3.18

LABEL maintainer="OpenSVC Ansible Team <ansible@opensvc.com>"
LABEL vendor1="OpenSVC"

COPY requirements.dev.txt /tmp
RUN apk add --update --no-cache ca-certificates \
                                cargo \
                                openssh-client \
                                build-base \
                                gcc \
                                g++ \
                                git \
                                make \
                                python3-dev \
                                py-pip \
                                libffi-dev \
                                rust \
                                shellcheck \
                                sshpass \
                                libressl-dev

RUN  pip install --upgrade pip 

RUN  pip install -r /tmp/requirements.dev.txt

RUN pip uninstall -y ansible-base

RUN python -m pip install https://github.com/ansible/ansible/archive/devel.tar.gz

RUN                             apk del -r --purge gcc make g++ &&\
                                rm -rf /source/* &&\
                                rm -rf /var/cache/apk/* &&\
                                rm -rf /tmp/*

COPY requirements.dev.yml /tmp/

RUN ansible-galaxy collection install -p /usr/share/ansible/collections -r /tmp/requirements.dev.yml

WORKDIR /opt
ADD ansible_collections/opensvc/ /opt/opensvc/

RUN ansible-galaxy collection build --force opensvc/cluster opensvc/app && \
    for i in *.tar.gz; do ansible-galaxy collection install $i -p /usr/share/ansible/collections; done

WORKDIR /examples

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["check"]
