---
# tasks file for unprovision_services

- name: Check cluster vip current config
  command: om cluster get --kw cluster.vip --eval
  register: osvc_cluster_vip
  changed_when: false
  failed_when: false

- name: Consider that vip is not configured
  set_fact:
    osvc_cluster_vip_is_configured: false

- name: Check if vip is actually configured
  set_fact:
    osvc_cluster_vip_is_configured: true
  when:
    - osvc_cluster_vip.stdout.find('None') == -1

- name: Display osvc_cluster_vip_is_configured variable content
  debug:
    var: osvc_cluster_vip_is_configured
    verbosity: 2

- name: Unconfigure cluster vip
  command: om cluster unset --kw cluster.vip
  when:
    - osvc_cluster_vip_is_configured|bool
    - inventory_hostname == ansible_play_hosts[0]

- name: Unconfigure cluster vip (scoped entries)
  command: om cluster unset --kw cluster.vip@{{ ansible_hostname }}
  when:
    - osvc_cluster_vip_is_configured|bool

- name: Consider that we do not need to purge anything
  set_fact:
    osvc_cluster_need_svc_purge: false
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Check if we actually need to purge something
  command: om '*/*/*+!*/*/cluster' ls | wc -l
  changed_when: false
  failed_when: false
  register: osvc_cluster_svc_count
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Update fact
  set_fact:
    osvc_cluster_need_svc_purge: true
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_svc_count.stdout != '0'

- name: Purge all OpenSVC services
  command: om '*/*/*+!*/*/cluster' purge --wait --time {{ osvc_svc_purge_wait_time }}
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_need_svc_purge|bool

- name: Check for actual service unprov
  command: om '*/*/*+!*/*/cluster' ls | wc -l
  changed_when: false
  failed_when: false
  register: osvc_cluster_svc_unprov_cmdres
  retries: "{{ osvc_svc_purge_retries }}"
  delay: "{{ osvc_svc_purge_delay }}"
  until: osvc_cluster_svc_unprov_cmdres.stdout == '0'
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - osvc_cluster_need_svc_purge|bool
