---
# handlers file for provision_cluster
- name: Reload sshd
  service:
    name: "{{ systemd_ssh_unit }}"
    state: reloaded

- name: restart docker service
  service:
    name: "{{ systemd_docker_unit }}"
    state: restarted
