---
# handlers file for provision_cluster
- name: Reload sshd
  ansible.builtin.service:
    name: "{{ systemd_ssh_unit }}"
    state: reloaded

- name: Restart docker service
  ansible.builtin.service:
    name: "{{ systemd_docker_unit }}"
    state: restarted
