- hosts: all
  any_errors_fatal: true
  gather_facts: true
  tasks:
    - name: Import role provision_cluster
      import_role:
        name: opensvc.cluster.provision_cluster
      vars:
        osvc_clustername: hyperopenx
        osvc_hb_timeout: 30s
        osvc_update_etc_hosts: true
        osvc_configure_webapp: false
        osvc_configure_vip: false

    - name: import role install_drbd
      import_role:
        name: opensvc.cluster.install_drbd

    - name: import role install_slapos_comp1
      import_role:
        name: opensvc.app.install_slapos_comp1
      vars:
        install_slapos_comp1_re6st_token: 284632nyrofmqsadcbxtheluiw
        install_slapos_comp1_data_size: 20GB
        install_slapos_comp1_token: 20250409.019-1E5B9D6
        install_slapos_comp1_computer_name: slaposcomp1ha10
        install_slapos_comp1_partition_number: 5
