---
# defaults file for install_dns
install_dns_service_namespace: system
install_dns_short_service_name: dns
install_dns_cfgmap_name: "{{ install_dns_service_namespace }}/cfg/{{ install_dns_short_service_name }}"
install_dns_service_name: "{{ install_dns_service_namespace }}/svc/{{ install_dns_short_service_name }}"

install_dns_cfg_server_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/dns/pdns.conf.template
install_dns_cfg_recursor_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/dns/recursor.conf.template
install_dns_cfg_configure_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/dns/configure
install_dns_svc_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/dns/dns.conf

# by default recursor allow the following subnets as requestors => 127.0.0.1/32,10.0.0.0/8,fd00::/112,::1
# if you need to add some more, fill in the variable below with patterns like:
# install_dns_cfg_recursor_allowed_subnets: '172.16.10.0/24'
# install_dns_cfg_recursor_allowed_subnets: '172.16.10.0/24,192.168.200.0/24'
install_dns_cfg_recursor_allowed_subnets: ''

# by default dns ip list is taken from host main ip
# when nodes are hidden by public ip different from node's ip
# ansible_host inventory variable can be used to specify the nodes public ip
install_dns_use_ip_from_ansible_host: false
