---

- name: Configure vg pool
  ansible.builtin.command:
    cmd: >
      om cluster config update
      --set pool#{{ install_pool_name }}.type={{ install_pool_type }}
  run_once: true
  register: install_pool_output
  changed_when: install_pool_output.rc == 0

- name: Configure vg pool backing lvm vg
  ansible.builtin.command:
    cmd: >
      om cluster config update
      --set pool#{{ install_pool_name }}.name={{ install_pool_vg }}
  run_once: true
  register: install_pool_output
  changed_when: install_pool_output.rc == 0
  when:
    - (install_pool_vg is defined) and (install_pool_vg|length > 0)
