#!/bin/bash 

source $1
 
om node wait --filter .monitor.services.\'${svcpath}\'.overall=${expected} --duration ${timeout} || {
    printf '{"changed": false, "failed": true, "msg": "%s is not %s after %s"}' "$svcpath" "$expected" "$timeout"
}

printf '{"changed": false, "msg": "%s is overall %s"}' "$svcpath" "$expected"
