---
# defaults file for install_envoy
install_envoy_osvc_envoy_service_namespace: system
install_envoy_osvc_envoy_short_service_name: envoy
install_envoy_osvc_envoy_cfgmap_name: "{{ install_envoy_osvc_envoy_service_namespace }}/cfg/{{ install_envoy_osvc_envoy_short_service_name }}"
install_envoy_osvc_envoy_service_name: "{{ install_envoy_osvc_envoy_service_namespace }}/svc/{{ install_envoy_osvc_envoy_short_service_name }}"

install_envoy_osvc_envoy_cfg_xds_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/igw_envoy/xds.yaml
install_envoy_osvc_envoy_svc_template: https://raw.githubusercontent.com/opensvc/opensvc_templates/main/igw_envoy/hostns.conf
