---
- name: Install elrepo channels for version 7
  ansible.builtin.yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_distribution_major_version|int == 7

- name: Install elrepo channels for version 8
  ansible.builtin.yum:
    name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_distribution_major_version|int == 8

- name: Install elrepo channels for version 9
  ansible.builtin.yum:
    name: https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm
    state: present
    disable_gpg_check: true
  when:
    - ansible_distribution_major_version|int == 9

- name: Install drbd packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  with_items:
    - kmod-drbd90
    - drbd90-utils
  when:
    - ansible_distribution_major_version|int <= 8

- name: Install drbd packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: true
  with_items:
    - kmod-drbd9x
    - drbd9x-utils
  when:
    - ansible_distribution_major_version|int > 8
