- hosts: all
  gather_facts: true
  tasks:
    - name: import role provision_cluster
      import_role:
        name: opensvc.cluster.provision_cluster
      vars:
        osvc_clustername: testcluster
        osvc_hb_timeout: 25s
        osvc_update_etc_hosts: true
