---

- name: Install common packages for sles
  community.general.zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python36
      - python36-requests
      - python36-crypto
      - python36-cryptography
      - sg3_utils
      - psmisc
  when:
    - (ansible_distribution_major_version|int < 15)

- name: Install common packages for sles (ver >= 15)
  community.general.zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker
      - psmisc
      - python3
      - python3-requests
      - python3-cryptography
      - python311
      - python311-requests
      - python311-cryptography
      - sg3_utils
  when:
    - (ansible_distribution_major_version|int >= 15)
