---
# defaults file for provision_cluster

# set to something unique
provision_cluster_clustername: demo

# time waited before considering hb as down
provision_cluster_hb_timeout: 20s

# update /etc/hosts to add each cluster node ip
# false: you deal with this setup by yourself
# true: you expect the playbook to do the config
provision_cluster_update_etc_hosts: false

# depending on your cluster setup, you may need to disable default docker behavior with iptables
# if false, do not change /etc/docker/daemon.json config file
# if true, override /etc/docker/daemon.json content with iptables=false
provision_cluster_deploy_docker_daemon_json: false

# when docker daemon config deployment is enabled, we need to restart the docker service
provision_cluster_systemd_docker_unit: 'docker.service'

# configure the cluster virtual ip
# recommended for streched vlans setup
# clients can connect to webapp/api using this floating ip
provision_cluster_configure_vip: false
provision_cluster_vip_addr: '1.2.3.4'
provision_cluster_vip_cidr_subnet: '24'
# vip ip addr will be configured on link vipnic@br-prd (displayed with "ip link list")
provision_cluster_vip_nic_name: 'vipnic'
provision_cluster_node_prd_nic: 'br0'
# public fqdn https://vip.domain.com:1215
provision_cluster_vip_external_fqdn: 'vip.domain.com'

# configure cluster ssh trust between nodes
# must be done either by collection or manually
provision_cluster_configure_ssh_trust: false
