---
# tasks file for install_backend_network

# Check if the backend network is already configured
- name: Check for backend network configuration
  ansible.builtin.shell:
    cmd: set -o pipefail && om net ls | grep -w {{ install_backend_network_subnet }}
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: _osvc_network_list
  run_once: true

# Configure backend network if not already present
- name: Configure backend network if not configured
  ansible.builtin.command:
    cmd: >
      om cluster set
      --kw network#{{ install_backend_network_subnet }}.type=routed_bridge
      --kw network#{{ install_backend_network_subnet }}.network={{ install_backend_network_subnet_range }}
      --kw network#{{ install_backend_network_subnet }}.ips_per_node={{ install_backend_network_subnet_ips_per_node }}
      --kw network#{{ install_backend_network_subnet }}.tunnel={{ install_backend_network_tunnel }}
  run_once: true
  register: output
  changed_when: output.rc == 0
  when: install_backend_network_subnet not in _osvc_network_list.stdout

- name: Display network configuration result
  ansible.builtin.debug:
    var: _network_is_configured
  args:
    verbosity: 2
