---
# tasks file for install_backend_network

# Check if the backend network is already configured
- name: Check for backend network configuration
  ansible.builtin.shell:
    cmd: set -o pipefail && om net ls | grep -w {{ osvc_backend_subnet_name }}
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false
  register: _osvc_network_list
  run_once: true

# Configure backend network if not already present
- name: Configure backend network if not configured
  ansible.builtin.command:
    cmd: >
      om cluster set
      --kw network#{{ osvc_backend_subnet_name }}.type=routed_bridge
      --kw network#{{ osvc_backend_subnet_name }}.network={{ osvc_backend_subnet_range }}
      --kw network#{{ osvc_backend_subnet_name }}.ips_per_node={{ osvc_backend_subnet_ips_per_node }}
      --kw network#{{ osvc_backend_subnet_name }}.tunnel={{ osvc_backend_tunnel }}
  run_once: true
  register: output
  changed_when: output.rc == 0
  when: osvc_backend_subnet_name not in _osvc_network_list.stdout

- name: Display network configuration result
  ansible.builtin.debug:
    var: _network_is_configured
  args:
    verbosity: 2
