---
- name: Add OpenSVC repository
  ansible.builtin.yum_repository:
    name: opensvc
    description: OpenSVC Repository
    baseurl: "{{ opensvc_repo_url }}"
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.opensvc.com/gpg.public.key.asc
    state: present
  when: ansible_os_family == "RedHat"

- name: Install common packages for RHEL/CentOS/Fedora (ver >= 8)
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - podman
      - psmisc
      - sg3_utils
  when:
    - ansible_distribution_major_version | int >= 8

- name: Install jq if not present
  ansible.builtin.package:
    name: jq
    state: present
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Install opensvc-server package
  ansible.builtin.dnf:
    name: opensvc-server
    state: present
    update_cache: true
    enablerepo: opensvc
    disablerepo: "*"
  become: true

- name: Update package facts
  ansible.builtin.package_facts:
    manager: auto

- name: List opensvc packages
  ansible.builtin.set_fact:
    paquets_osvc: "{{ ansible_facts.packages | dict2items | selectattr('key', 'search', 'opensvc') | list }}"

- name: Debug OpenSVC installed package
  ansible.builtin.debug:
    msg: "Installed OpenSVC package: {{ paquets_osvc }}"
    verbosity: 2

- name: Enable and start opensvc-server.service
  ansible.builtin.service:
    name: opensvc-server.service
    enabled: true
    state: started
