---
- name: Add OpenSVC repository for Debian-based systems
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] {{ opensvc_repo_url }} default all"
    state: present
  when: ansible_os_family == "Debian"

- name: Update packages list
  ansible.builtin.apt:
    update_cache: yes

- name: Install common packages for ubuntu/deb
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker.io
      - runc
      - sg3-utils

- name: Install opensvc-server package
  ansible.builtin.apt:
    name: opensvc-server
    state: present
    update_cache: yes

- name: Enable opensvc-agent.service unit file
  ansible.builtin.service:
    name: opensvc-agent.service
    enabled: true
    state: started

