---
- name: Set the OpenSVC repository URL for SLES
  ansible.builtin.set_fact:
    opensvc_repo_url: "https://packages.opensvc.com/dev/opensvc/v3/sles/{{ ansible_distribution_major_version }}/x86_64/rpms/"

- name: Add OpenSVC repository for SLES
  community.general.zypper_repository:
    name: opensvc
    description: OpenSVC Repository
    autorefresh: true
    repo: "{{ opensvc_repo_url }}"
    enabled: true
    state: present
    disable_gpg_check: true

- name: Validate OpenSVC repository configuration
  ansible.builtin.shell: "zypper lr -u | grep '{{ opensvc_repo_url }}'"
  register: repo_validation
  changed_when: false
  failed_when: repo_validation.rc != 0

- name: Refresh repository cache
  ansible.builtin.command:
    cmd: "zypper --non-interactive refresh"
  changed_when: false

#- name: Update packages list and install updates
#  community.general.zypper:
#    name: "*"
#    state: latest
#    update_cache: true

- name: Install common packages for SLES
  community.general.zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - podman
      - psmisc
      - sg3_utils

- name: Install opensvc-server package
  community.general.zypper:
    name: opensvc-server
    state: latest
    force: yes
  become: true

- name: Check installed OpenSVC package
  ansible.builtin.shell: "rpm -qa | grep opensvc"
  register: opensvc_package
  changed_when: false

- name: Debug OpenSVC installed package
  ansible.builtin.debug:
    msg: "Installed OpenSVC package: {{ opensvc_package.stdout }}"

- name: Check if opensvc-agent is running
  ansible.builtin.command:
    cmd: "systemctl is-active opensvc-agent.service"
  register: service_status
  changed_when: false
  failed_when: service_status.stdout != "active"
