---
- name: Add OpenSVC repository for Ubuntu-based systems
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] {{ opensvc_repo_url }} uat-opensvc-v3-{{ ansible_facts['lsb']['codename'] }} main"
    state: present
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Update packages list
  ansible.builtin.apt:
    update_cache: true

- name: Install common packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - docker.io
      - runc
      - sg3-utils

- name: Install opensvc-server package
  ansible.builtin.apt:
    name: opensvc-server
    state: present
    update_cache: true

- name: Enable opensvc-server.service unit file
  ansible.builtin.service:
    name: opensvc-server.service
    enabled: true
    state: started
