---

- name: Ensure service is running on first node
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} takeover --wait"
  register: install_slapos_comp1_output
  changed_when: install_slapos_comp1_output.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Get fs install root
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} eval --kw fs#0.mnt"
  register: install_slapos_comp1_output
  changed_when: install_slapos_comp1_output.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Remove slapos crontab on first node
  ansible.builtin.file:
    path: /etc/cron.d/slapos-node
    state: absent

- name: Set fact on slapos existence
  ansible.builtin.set_fact:
    install_slapos_comp1_slapos_root: "{{ install_slapos_comp1_output.stdout }}/slapos"
    install_slapos_comp1_slapos_etc: "{{ install_slapos_comp1_output.stdout }}/slapos/etc/opt/slapos"
    install_slapos_comp1_slapos_log: "{{ install_slapos_comp1_output.stdout }}/slapos/log"
    install_slapos_comp1_slapos_soft: "{{ install_slapos_comp1_output.stdout }}/slapos/opt/slapgrid"
    install_slapos_comp1_slapos_inst: "{{ install_slapos_comp1_output.stdout }}/slapos/srv/slapgrid"
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Check if configuration already exists
  ansible.builtin.stat:
    path: "{{ install_slapos_comp1_slapos_etc }}/slapos.cfg"
  register: install_slapos_comp1_slapos_conf
  when:
    - inventory_hostname == ansible_play_hosts[0]

- name: Configure slapos with slapos node register
  ansible.builtin.shell:
    cmd: |
      slapos node register \
        --cfg {{ install_slapos_comp1_slapos_etc }}/slapos.cfg \
        --token {{ install_slapos_comp1_token }} \
        --master-url {{ install_slapos_comp1_master_url }} \
        --master-url-web {{ install_slapos_comp1_web_master_url }} \
        --interface-name {{ install_slapos_comp1_interface_name }} \
        --partition-number {{ install_slapos_comp1_partition_number }} \
        {{ install_slapos_comp1_computer_name }} \
        --software-root {{ install_slapos_comp1_slapos_soft }} \
        --instance-root {{ install_slapos_comp1_slapos_inst }}
    executable: /bin/bash
  register: install_slapos_comp1_node_register
  changed_when: install_slapos_comp1_node_register.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Complete slapos config - set computer_xml path
  ansible.builtin.replace:
    path: "{{ install_slapos_comp1_slapos_etc }}/slapos.cfg"
    regexp: 'computer_xml = /opt/slapos/slapos.xml'
    replace: 'computer_xml = {{ install_slapos_comp1_slapos_root }}/slapos.xml'
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Complete slapos config - set log path
  ansible.builtin.replace:
    path: "{{ install_slapos_comp1_slapos_etc }}/slapos.cfg"
    regexp: '/opt/slapos/log'
    replace: '{{ install_slapos_comp1_slapos_log }}'
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Complete slapos config - set pid_folder path
  ansible.builtin.replace:
    path: "{{ install_slapos_comp1_slapos_etc }}/slapos.cfg"
    regexp: 'pid_folder = /srv/slapgrid/var/run'
    replace: 'pid_folder = {{ install_slapos_comp1_slapos_inst }}/var/run'
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Enable slapos app management with OpenSVC
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} enable --rid app#1"
  register: install_slapos_comp1_enable
  changed_when: install_slapos_comp1_enable.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Start slapos app management with OpenSVC
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} start --rid app#1"
  register: install_slapos_comp1_start
  changed_when: install_slapos_comp1_start.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Force status evaluation (v2)
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} print status -r"
  changed_when: false
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists
    - install_slapos_comp1_opensvc_major is defined and install_slapos_comp1_opensvc_major | int == 2

- name: Force status evaluation (v3)
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} print status --output flat"
  changed_when: false
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists
    - install_slapos_comp1_opensvc_major is defined and install_slapos_comp1_opensvc_major | int == 3

- name: Enable slapos task management with OpenSVC
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} enable --rid task"
  register: install_slapos_comp1_output
  changed_when: install_slapos_comp1_output.rc == 0
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists

- name: Display final service state (v2)
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} print status -r"
  changed_when: false
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists
    - install_slapos_comp1_opensvc_major is defined and install_slapos_comp1_opensvc_major | int == 2

- name: Display final service state (v3)
  ansible.builtin.command: "om {{ install_slapos_comp1_svcpath }} print status --output flat"
  changed_when: false
  failed_when: false
  when:
    - inventory_hostname == ansible_play_hosts[0]
    - not install_slapos_comp1_slapos_conf.stat.exists
    - install_slapos_comp1_opensvc_major is defined and install_slapos_comp1_opensvc_major | int == 3
