---

- name: Check if re6st has already been installed
  ansible.builtin.shell:
    cmd: which re6stnet
  args:
    executable: /bin/bash
  register: re6stnet_command
  failed_when: false
  changed_when: false

- name: Set fact according to actual re6st cfg existence
  ansible.builtin.set_fact:
    re6st_is_installed: "{{ re6stnet_command.rc == 0 }}"
#  when:
#    - re6stnet_command.rc != 0

- name: Ensure /etc/systemd is clean
  ansible.builtin.shell:
    cmd: >
      set -o pipefail &&
      find /etc/systemd -name re6stnet.service -delete
  args:
    executable: /bin/bash
  failed_when: false
  register: find_command
  changed_when: find_command.rc == 0
  when:
    - not re6st_is_installed

- name: Download re6st installer
  ansible.builtin.get_url:
    url: "{{ install_slapos_comp1_re6st_installer_url }}"
    dest: /root/re6st.installer
    mode: '0750'
    force: true
  when:
    - not re6st_is_installed

- name: Add extra_vars to avoid being prompted for re6st token and router adv
  ansible.builtin.lineinfile:
    path: /root/re6st.installer
    regexp: ^(ansible-playbook gnet-re6stnet.yml -i hosts --connection=local)$
    line: >
      ANSIBLE_LOG_PATH=~/ansible.re6st.log \g<1>
      --extra-vars re6sttoken="notoken"
      --extra-vars location={{ install_slapos_comp1_re6st_location }}
      --extra-vars enable_router_advertisement={{ install_slapos_comp1_re6st_router_advertisement }}
    backrefs: true
  when:
    - not re6st_is_installed

- name: Launch re6st installer
  ansible.builtin.command: /root/re6st.installer
  register: re6stlog
  changed_when: re6stlog.rc == 0
  when:
    - not re6st_is_installed

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: re6stlog.stdout_lines
    verbosity: 2
  when:
    - not re6st_is_installed

- name: Get Service Status
  ansible.builtin.systemd:
    name: "re6stnet.service"
  register: re6st_service_status
  when:
    - not re6st_is_installed

- name: Print systemd service status
  ansible.builtin.debug:
    var: re6st_service_status.status.ActiveState
    verbosity: 2
  when:
    - not re6st_is_installed

- name: Disable and mask re6stnet.service systemd unit
  ansible.builtin.systemd:
    name: re6stnet.service
    enabled: false
    masked: true
    state: stopped
