---

- name: Check if slapos has already been installed
  ansible.builtin.shell:
    cmd: which slapos
  args:
    executable: /bin/bash
  register: slapos_command
  failed_when: false
  changed_when: false

- name: Set fact according to slapos existence
  ansible.builtin.set_fact:
    slapos_is_installed: "{{ slapos_command.rc == 0 }}"

- name: Download slapos installer
  ansible.builtin.get_url:
    url: "{{ install_slapos_comp1_installer_url }}"
    dest: /root/slapos.installer
    mode: '0750'
    force: true
  when:
    - not slapos_is_installed

- name: Add extra_vars to avoid being prompted for playbook variables
  ansible.builtin.lineinfile:
    path: /root/slapos.installer
    regexp: ^(ansible-playbook slapos-base.yml -i hosts --connection=local)
    line: >
      ANSIBLE_LOG_PATH=~/ansible.slapos.log \g<1>
      --extra-vars slapos_master_url={{ install_slapos_comp1_master_url }}
      --extra-vars slapos_web_master_url={{ install_slapos_comp1_web_master_url }}
      --extra-vars computer_name="noname"
      --extra-vars slapostoken="notoken"
      --extra-vars interface_name={{ install_slapos_comp1_interface_name }}
      --extra-vars partition_number={{ install_slapos_comp1_partition_number }}
    backrefs: true
  when:
    - not slapos_is_installed

- name: Launch slapos installer on both nodes
  ansible.builtin.command: /root/slapos.installer
  register: slaposlog
  changed_when: slaposlog.rc == 0
  when:
    - not slapos_is_installed
